stages:
  - mirror

mirror_to_github:
  stage: mirror
  only:
    - main
  script:
    - git config --global user.email "Yasindu007@example.com"
    - git config --global user.name "Yasindu007"
    - git clone --mirror https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/Yasindu007/loon-labs-movie-explorer.git
    - cd loon-labs-movie-explorer.git
    # Different approach to authentication with GitHub
    - |
      if [ -n "$GITHUB_TOKEN" ]; then
        echo "Using GITHUB_TOKEN for authentication"
        git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/Yasindu007/loon-labs-movie-explorer.git
      else
        echo "GITHUB_TOKEN is not set"
        exit 1
      fi
    - git push --mirror github